services:
  app:
    container_name: container_app
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    command: php-fpm
    restart: unless-stopped

  node:
    container_name: container_node
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - ./src:/var/www/html
    command: npm install
    restart: unless-stopped

  webserver:
    container_name: container_web
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    container_name: container_db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: sample_laravel
      MYSQL_ROOT_PASSWORD: sample&laravel
      MYSQL_PASSWORD: laravelSample
      MYSQL_USER: laraveluser
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  dbdata: